name: Linter and Telegram

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:

jobs:
  build:
    name: Run CSS linter
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TG_ID }}
          token: ${{ secrets.TG_TOKEN }}
          message: |
            ${{ github.actor }} created a new commit: ${{ github.event.commits[0].message }}
            Commit link: https://github.com/${{ github.repository }}/commit/${{ github.sha }}
            Repository: https://github.com/${{ github.repository }}
            
            CI/CD GitHub Actions: https://github.com/${{ github.repository }}/actions
            Workflow run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Stylelint
        run: npm install stylelint

      - name: Lint CSS files
        run: npx stylelint "**/*.css"

